---
abstract: 'Generate HTML tags in an easy way'
author:
  - Chenryn<rao.chenlin@gmail.com>
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-TagHelper
no_index:
  directory:
    - t
    - inc
    - t
requires:
  Carp: 0
  DateTime: 0
  HTML::Element: 0
  HTML::Entities: 0
  Moo: 0
  Test::More: 0
resources:
  repository: https://github.com/chenryn/HTML-TagHelper.git
version: 0.02
